### ISSUE TITLE
Getting error response from functions when creating payment intent. 

### ISSUE THREAD

**Issue by dshukertjr** [thorwebdev/expo-stripe-payments-with-supabase-functions#1]
While I was creating Flutter sample app, I noticed an error on the function's end. 

It seems like the call to supabase [here](https://github.com/thorwebdev/expo-stripe-payments-with-supabase-functions/blob/main/supabase/functions/payment-sheet/index.ts#L24) is failing with the following error message

`
FetchError: error sending request for url ([https://ezkbryeecvynphnrwzhb.supabase.co/rest/v1/customers?select=*]()): error trying to connect: dns error: failed to lookup address information: Name or service not known
`

**Comment by thorwebdev** [comment]
@dshukertjr sorry, the project has changed to 

```js
const supabaseUrl = "https://gvkuljvaukfrwmrythfi.supabase.co";
const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2a3VsanZhdWtmcndtcnl0aGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg1NTA4MjQsImV4cCI6MTk2NDEyNjgyNH0.SJpObtyvXNXiVXFBtNED8K7dry5pnaHN7tswyYGQU00";

```

**Comment by dshukertjr** [comment]
Ah, makes sense! Thanks @thorwebdev !

**Comment by dshukertjr** [comment]
@thorwebdev I was about to ask about that as well! Thanks!

**Comment by dshukertjr** [comment]
Everything worked beautifully! Thanks again!

**Comment by thorwebdev** [comment]
I've added you to the project org, you should be able to access also. PS: just pushed the latest readme changes up that might be helpful for you: https://github.com/thorwebdev/expo-stripe-payments-with-supabase-functions/commit/a8e7fb0ef58aa73f1c7fcda467c5353abc01e0a4
